//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allegory.Standard.Filter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Allegory.Standard.Filter.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between operator must array and have two values.
        /// </summary>
        public static string BetweenValueError {
            get {
                return ResourceManager.GetString("BetweenValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name cannot null.
        /// </summary>
        public static string ColumnNullError {
            get {
                return ResourceManager.GetString("ColumnNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} type does not implement from {1}.
        /// </summary>
        public static string ImplementError {
            get {
                return ResourceManager.GetString("ImplementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In operator must array and have one or more values.
        /// </summary>
        public static string InValueError {
            get {
                return ResourceManager.GetString("InValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a member of type {1}.
        /// </summary>
        public static string MemberOfTypeError {
            get {
                return ResourceManager.GetString("MemberOfTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unsupported {1} operator.
        /// </summary>
        public static string UnsupportedOperatorError {
            get {
                return ResourceManager.GetString("UnsupportedOperatorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot null.
        /// </summary>
        public static string ValueNullError {
            get {
                return ResourceManager.GetString("ValueNullError", resourceCulture);
            }
        }
    }
}
